language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update
install:
  - sudo apt-get install python-qt4 python-dev libx11-dev libxtst-dev xvfb
  - pip install -r requirements.txt
  - python setup.py install
before_script:
  - cd tests
  - python test_server.py &
script: ../xvfb-run nosetests
